name: Docker-AWS
on:
  push:
    branches: [ "main1 ]
  pull_request:
    branches: [ "main" ]
env:
  #REGISTRY: ghcr.io
  REGISTRY: ${{ secrets.REPO_URI }}
  #account/repo
  IMAGE_NAME: ${{ github.repository }}-${{ github.head_ref || github.ref_name }}

jobs:
  
  build:
    runs-on: ubuntu-latest 
    environment: ${{github.head_ref || github.ref_name }}
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - uses: actions/checkout@v4
      - name: create .env for file build
        run:  echo "$ENV_TEXT" > .env 
        env:
            ENV_TEXT: ${{vars.ENV_TEXT}}
       
      -  name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest  
          
      # login against a container registry ${{env.REGISTRY}}   
      - name: Login to GHCR or ECR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3  
        with:
          #registry: ${{env.REGISTRY}} 
          #password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ secrets.REPO_URI }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Build and push docker image to the container registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}  
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: delete all untaged versions
        uses: actions/delete-package-versions@v5
        with: 
           package-name: 'my-portfolio-${{github.head_ref || github.ref_name }}'
           package-type: 'container'
           min-versions-to-keep: 3
           delete-only-untagged-versions: 'true' 
           
      
