
name: Docker-AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}  # Use secret for AWS Region
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  IMAGE_NAME: ${{ github.repository }}-${{ github.head_ref || github.ref_name }}
  
jobs:
  
  build:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create .env for file build
        run: echo "$ENV_TEXT" > .env 
        env:
          ENV_TEXT: ${{ vars.ENV_TEXT }}
       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Use OIDC Role for this repo
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: portfolioapp
          #IMAGE_TAG: ${{ github.sha }}
          IMAGE_TAG: ${{ github.head_ref || github.ref_name }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
      - name: Set output for image
        id : image-name
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Delete all untagged versions
        uses: actions/delete-package-versions@v5
        with: 
          #package-name: '${{ steps.image-name.outputs.package }}'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged-versions: 'true'
